# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
# -*- encoding: utf-8 -*-

# stub: immutables 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "immutables".freeze
  s.version = "0.1.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.metadata = {"bug_tracker_uri" => "https://github.com/copiousfreetime/immutables/issues", "changelog_uri" => "https://github.com/copiousfreetime/immutables/blob/master/HISTORY.md", "homepage_uri" => "https://github.com/copiousfreetime/immutables", "label" => "immutables", "rubygems_mfa_required" => "true", "source_code_uri" => "https://github.com/copiousfreetime/immutables"} if s.respond_to? :metadata=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeremy Hinegardner".freeze]
  s.bindir = "exe".freeze
  s.cert_chain = ["/Users/jeremy/.local/share/gem/gem-public_cert.pem".freeze]
  s.description = "A library to load immutable collections of data from files into your application.".freeze
  s.email = "jeremy@copiousfreetime.org".freeze
  s.extra_rdoc_files = ["CONTRIBUTING.md".freeze, "HISTORY.md".freeze, "Manifest.txt".freeze, "README.md".freeze]
  s.files = ["CONTRIBUTING.md".freeze, "HISTORY.md".freeze, "LICENSE".freeze, "Manifest.txt".freeze, "README.md".freeze, "Rakefile".freeze, "lib/immutables.rb".freeze]
  s.homepage = "http://github.com/copiousfreetime/immutables".freeze
  s.licenses = ["ISC".freeze]
  s.rdoc_options = ["--main".freeze, "README.md".freeze, "--markup".freeze, "tomdoc".freeze]
  s.required_ruby_version = Gem::Requirement.new("~> 3.1".freeze)
  s.summary = "A library to load immutable collections of data from files into your application.".freeze
  s.signing_key = "/Users/jeremy/.local/share/gem/gem-private_key.pem".freeze
end
